server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ms-authentication}
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false

logging:
  level:
    root: INFO # PROD - INFO
    co.com.pragma: DEBUG # PROD - INFO/DEBUG
    org.springframework.r2dbc: WARN
    io.r2dbc.postgresql.QUERY: INFO # PROD - INFO O WARN
    io.r2dbc.postgresql.PARAM: WARN # PROD - WARM O OFF

adapters:
  r2dbc:
    host: ${ADAPTERS_R2DBC_HOST:localhost}
    port: ${ADAPTERS_R2DBC_PORT:5433}
    database: ${ADAPTERS_R2DBC_DATABASE:crediya_db}
    schema: ${ADAPTERS_R2DBC_SCHEMA:public}
    username: ${ADAPTERS_R2DBC_USERNAME:crediya}
    password: ${ADAPTERS_R2DBC_PASSWORD:crediya2025}
  profiles:
    include: ${ADAPTERS_PROFILES_INCLUDE:}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:"http://localhost:4200,http://localhost:8080"}

routes:
  paths:
    users: "/api/v1/usuarios"
    usersById: "/api/v1/usuarios/{id}"
    existsByEmail: "/api/v1/usuarios/email/{email}"
    existsByIdNumber: "/api/v1/usuarios/idNumber/{idNumber}"
    login: "/api/v1/login"
    hello: "/hello"
    actuator: "/actuator/health"

jwt:
  secret: ${JWT_SECRET:GKU2sCyjHN2D4KXdLKsxRn3UDKI1TjTdP3pxzMzfIE8=}
  expiration: ${JWT_EXPIRATION:3600}